### ISSUE TITLE
ValidationError should be part of public API

### ISSUE THREAD

**Issue by itamarst** [itamarst/eliot#146]
Serializers are explicitly documented as allowing to raise it.

**Comment by exarkun** [comment]
Yes please

**Comment by exarkun** [comment]
Also I would like this feature along with Python 2.7 support. :/

**Comment by itamarst** [comment]
Hm. If I stop doing feature updates to the version that has 2.7, you can just use the private path and be confident it won't change... Or do you need to support both Python 2 and Python 3?

**Comment by exarkun** [comment]
I don't need Python 3 _yet_.  Maybe next year.  I am trying to use Eliot with Tahoe-LAFS which is currently Python 2 only but which might be ported to Python 3 sometime this year.

**Comment by exarkun** [comment]
(So for now I am okay using the private name and I'm pinning 1.6.0 anyway due to the need to keep Python 2.7 compatibility.)
