### ISSUE TITLE
Public API for parsing Eliot log entries

### ISSUE THREAD

**Issue by jml** [itamarst/eliot#181]
Eliot should have a public API for taking a stream of log entries and turning them into some sort of Python tree-like structure of actions and messages, so that Eliot logs can be readily analyzed and used by Python programs.

https://github.com/jonathanj/eliottree has one sort of implementation of this, https://github.com/ClusterHQ/eliot/blob/master/eliot/testing.py another, and https://github.com/jml/trial-eliot/blob/machinist-spike/eliotreporter/_parse.py another still.

The API should have separate layers:
1. take line-separated JSON objects and turn them into a stream of dictionaries
2. take a stream of dictionaries and turn them into a stream of logged messages
3. take a stream of logged messages and turn them into logged actions and logged messages

I propose making a new public `eliot.parse` module that provides all of these layers in a composable fashion.

https://github.com/jml/trial-eliot/blob/machinist-spike/eliotreporter/_parse.py is my first, incomplete attempt at this. It makes certain implementation calls that are open to judgement:
- two new types: `Message` and `Action`
- both provide certain fixed fields corresponding to core eliot concepts (e.g. `timestamp`, `entry_type`)
- `Action` allows for incomplete actions
- `make_nested_actions` assumes messages have been restricted to one task and sorted within that.
  
  I don't know what to do with the existing `LoggedAction` and `LoggedMessage` classes in `eliot.testing`. Options include:
- Move them to `eliot.parse`, make them available under `eliot.testing`
- Make new, distinct classes in `eliot.parse` that have APIs that are better suited to general purpose use. (e.g. expose the `task_uuid` or duration of an action), and either
  - deprecate the `eliot.testing` versions, or 
  - leave the `eliot.testing` versions as-is, and emphasize that they are for testing only

Give me a little bit of direction, and I'll provide a PR to add this to eliot.

**Comment by jml** [comment]
I wrote [my spike](https://github.com/jml/trial-eliot/blob/machinist-spike/eliotreporter/_parse.py) without reference to eliottree or `eliot.testing`. I was thinking we could take the best aspects of each and combine  them.

**Comment by jonathanj** [comment]
This would really be great to have. Sorry the eliottree tree code is a terribly hacky mess.

**Comment by jml** [comment]
Notes from  IRC:

* make sure we can handle a stream of out-of-order messages
* avoid drift between parser and serializer

**Comment by jml** [comment]
See also jonathanj/eliottree#21.

**Comment by itamarst** [comment]
I'm going to build a private in-memory API for use by flamegraphs code in #223.

**Comment by itamarst** [comment]
Done a while ago (`eliot.parse`).
