### ISSUE TITLE
Generators (and generator-based APIs like inlineCallbacks) don't work well with current implicit context

### ISSUE THREAD

**Issue by itamarst** [itamarst/eliot#259]
See #201 for example.

@jonathanj was talking about an explicit context API, where you just pass it around. That would be one solution.

Another is a decorator to be added to generators that deals with reinstating correct context.

At a minimum some documentation is probably called for.

**Comment by itamarst** [comment]
https://github.com/altendky/st/blob/3802c170e4f0c01f2324474e2a32762a818221d3/epyqlib/twisted/cancalibrationprotocol.py#L569 another example

**Comment by GaretJax** [comment]
Are there any ways around this? Would I be able to implement such a decorator without having to do any changes to eliot itself?

**Comment by itamarst** [comment]
Yes, it's probably just a decorator that returns a ... wrapper generator that somehow pops context on yield and restores on it on next(). I suspect hardest part is just figuring out the correct DTRT semantics, not actually implementing the code.

**Comment by GaretJax** [comment]
Is this something which could work generally with Twisted? https://github.com/twisted/twisted/blob/trunk/src/twisted/python/context.py

By using that, it might be possible to even avoid the need to `DeferredContext`.

I'll let you know if I get something working.

**Comment by itamarst** [comment]
That won't work, sorry. That's not fundamentally different than Eliot's context implementation, so it won't work any better (and it won't help replace `DeferredContext` either).

**Comment by GaretJax** [comment]
Yeah, figured that out in the meantime.

**Comment by itamarst** [comment]
What you actually need is something more like Node's https://datahero.com/blog/2014/05/22/node-js-preserving-data-across-async-callbacks/ - there are some PEPs being discussed for Python 3.7.

**Comment by exarkun** [comment]
I've taken a stab at making something like Eliot support for Twisted's inlineCallbacks API.  This does include a generator function decorator which might be more generally useful ... or not, I'm not sure.

Anyway, here's what I have:

https://github.com/tahoe-lafs/tahoe-lafs/blob/609af9ce183e0a64a56187538e5488c3f2016cfd/src/allmydata/test/eliotutil.py#L110-L210

There are clearly some drawbacks to the implementation but perhaps these could be mitigated either by inclusion in Eliot or by the introduction of certain new helpers by Eliot.
