### ISSUE TITLE
Generic coroutine support

### ISSUE THREAD

**Issue by itamarst** [itamarst/eliot#290]
Currently Eliot DTRT for asyncio coroutines only. It would be good to support all event loops (Twisted, Tornado, trio, curio, etc..)

One option: https://docs.python.org/3/library/sys.html#sys.set_coroutine_wrapper

In Python 3.7 might have context support, which would help too.

**Comment by knowsuchagency** [comment]
Along these lines, it would be great if we had a way to configure output using standard coroutines. 

i.e.

```python3
import json, sys
from eliot import add_destinations

async def coroutine(message):
    print(message)

add_destinations(coroutine)
```

**Comment by itamarst** [comment]
`contextvars` are the long term solution it seems:

1. It's in Python 3.7.
2. Backported to 3.6 (or even earlier?) in PyPI.
3. Trio uses them already, so supporting them will automatically add Trio.
4. Hopefully Tornado and Twisted will follow.
5. Curio sounds like it's not production-oriented so can be ignored.

**Comment by itamarst** [comment]
https://github.com/fantix/aiocontextvars would support Python 3.5 and later for `asyncio`.

**Comment by jtrakk** [comment]
I didn't even realize Eliot had support for some coroutines as destinations, that would be very cool. My log outputs are currently synchronous.

If I'm understanding right, that would allow something like 

```python
async def receive(request):
    async with eliot.start_action():
        async with trio.open_nursery() as nursery:
            nursery.start_soon(one_handler, request)
            nursery.start_soon(another_handler, request)

eliot.add_destinations(async_json_to_stderr)
```

and the main difference from the current api is that Action/Message would need async methods. Vaguely like...

```python
class Action:

    def __init__(self, **data):
        self.data = data

    async def __aenter__(self):
        await log_to_destinations(self.data)

    async def __aexit__(self, *args):
        await log_all_destinations(self.data)


async def log_to_all_destinations(data):
    for dest in destinations:
        await dest(**data)
```

**Comment by itamarst** [comment]
Eliot doesn't support coroutines as destinations, it supports having the action context track coroutines correctly (i.e. each coroutine has its own action stack). If you'd like an async destination support, could you open another ticket for that?

**Comment by jtrakk** [comment]
> If you'd like an async destination support, could you open another ticket for that?

Opened https://github.com/itamarst/eliot/issues/395

**Comment by itamarst** [comment]
Thanks!

**Comment by itamarst** [comment]
Looks like Trio uses https://pypi.org/project/contextvars/ for Python 3.5 and 3.6, so we should use that for compatibility. We can drop Python 3.4 support, it's just been end-of-lifed.
