### ISSUE TITLE
Make eliot._parse public so eliot-tree isn't depending on private API

### ISSUE THREAD

**Issue by itamarst** [itamarst/eliot#328]
`eliot-tree` depends on `eliot._parse`, which is private. Really, it's a stable API, and it should be useful to others as well.

So:

1. Make it public.
2. Add backwards compat `eliot._parse` for old eliot-tree installs.
3. Document it, at least a little.

CC @jonathanj

**Comment by jonathanj** [comment]
Sounds good to me. The only thing that occurs to me is that the minimum Eliot version that eliot-tree depends on would jump up from 0.12.0 to 1.6.0, but any users who can't upgrade Eliot can still continue using older versions of eliot-tree.
