### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by itamarst** [itamarst/eliot#341]
Python 2 is becoming a maintenance burden, given limited time to spend on the project. So I would like to drop it from future releases. In order to do so we need:

* [x] Stable API for `eliot-tree`, assuming it will continue to support Python 2. I think this just means making `eliot._parse` into `eliot.parse`. @jonathanj ?
* [ ] Documentation saying "Python 2 users should pin to release X.Y by doing `eliot<X.(Y+1)` in setup.py or requirements.txt" with final version.
* [x] Come up with a maintenance policy and fix it. Probably it'll be "only critical bugs will be fixed for Python 2 version, as point releases of X.Y".
* [x] Add `python_requires` to setup that indicates minimum version (can test in test PyPI).
* [x] Make sure releases are done with twine and recent version of setuptools (make dev requirements have new version of setuptools as minimum).
* [ ] Remove Python 2 metadata.
* [ ] Remove Python 2 from tox and travis.
* [ ] Update README

**Comment by jonathanj** [comment]
That sounds right to me, @itamarst. It might be prudent to review what else will become public when renaming the module

**Comment by itamarst** [comment]
It's done.
