### ISSUE TITLE
Add an API that can be called directly at the end of a test (eg in tearDown) to validate logging

### ISSUE THREAD

**Issue by exarkun** [itamarst/eliot#364]
I would like to apply generic serialization validation to all tests in a particular `TestCase`.  I could decorate every test with `@capture_logging(None)`.  It would be easier if I could instead just call some Eliot API in my `tearDown` (or as a cleanup function with `addCleanup`).  Perhaps this would need to be paired with some `setUp` API (I don't know).  That would be fine.  It still means two changes to my test suite instead of N.

**Comment by exarkun** [comment]
For example, perhaps:

```
class FooTests(TestCase):
    def setUp(self):
        validator = eliot.testing.get_ready_for_validation()
        self.addCleanup(eliot.testing.validator.validate_it_now)
```

**Comment by exarkun** [comment]
I suppose a class decorator could be another approach.

```
@eliot.testing.capture_logging_for_all_tests(None)
class FooTests(TestCase):
    ...
```

**Comment by exarkun** [comment]
Having an API I can call at any point I want would also make this kind of testing more Twisted-friendly, I think.  As far as I can tell, test methods that return a Deferred don't interact nicely with `@capture_logging`.

**Comment by itamarst** [comment]
OK, makes sense.
