### ISSUE TITLE
Point to the call site where a log mesage that fails validation was emitted

### ISSUE THREAD

**Issue by exarkun** [itamarst/eliot#365]
The traceback associated with a validation failure is pretty much useless.  It points to test runner innards and Eliot innards.  It doesn't point to the call site where the log message was emitted.  It doesn't even say what the action or message type was.  It only reports the field that failed validation.

Debugging validation failures would be easier with an action or message type.  It would be _much_ easier with a filename and line number.

I imagine there are many good reasons not to collect this information during normal operation but I think it may be feasible to collect when running with the intent of validating.

**Comment by itamarst** [comment]
See #324 for sketch of relevant implementation.

**Comment by itamarst** [comment]
Another alternative to adding the location to the message is doing basic validation immediately when the message is logged... are you using the type system, or is this some other form of validation failure?

**Comment by exarkun** [comment]
I am using the type system, yea.
