### ISSUE TITLE
DeferredContext.addCallbacks isn't signature-compatible with Deferred.addCallbacks

### ISSUE THREAD

**Issue by exarkun** [itamarst/eliot#366]
It is allowed to `d.addCallbacks(f)` though there's no benefit to this over `d.addCallback(f)` that I know of.  However, since it's allowed, surprise, someone does it.

When the `Deferred` `d` is replaced with a `DeferredContext`, though, this fails because `DeferredContext.addCallbacks` requires an errback.

**Comment by itamarst** [comment]
Want to submit a quick patch?

**Comment by exarkun** [comment]
Sure
