### ISSUE TITLE
Support outputting times in local timezone in eliot-prettyprint

### ISSUE THREAD

**Issue by sujit** [itamarst/eliot#428]
Currently, eliot stores the event timestamps as per UTC which is great but when (as a custom requirement), someone wants to view the events based on the local machine's local time zone, _eliot-tree_ or eliot module (_start_action_) itself doesn't provide such functionalities from that aspect.

Needless to say, UTC timestamps are global and widely acceptable but sometimes due to some custom requirements, this option certainly helps.

If anything as such can be added to _start-action_ or perhaps an additional command line parameter to _eliot-tree_ itself, that would be great!

-Sujit

**Comment by itamarst** [comment]
Changing the output is probably better than changing what's stored. I opened separate issue for eliot-tree, and will focus this one on eliot-prettyprint.
