### ISSUE TITLE
Eliot-tree link in reading.rst is malformed

### ISSUE THREAD

**Issue by jonathanj** [itamarst/eliot#444]
The sentence below is rendered incorrectly and does not end up hyperlinking eliot-tree. I'm not actually sure why, the syntax looks fine to me but it might be caused by nesting the inline styles? The other hyperlink in the document seems fine.

>Additionally, the highly recommended third-party `eliot-tree`_ tool renders JSON-formatted Eliot messages into a tree visualizing the tasks' actions.

https://eliot.readthedocs.io/en/stable/reading/reading.html

**Comment by itamarst** [comment]
Thanks for the bug report.
