### ISSUE TITLE
Can we customize the time zone of the log timestamp ?

### ISSUE THREAD

**Issue by StevenLianaL** [itamarst/eliot#455]

**Comment by itamarst** [comment]
Both `eliot-prettyprint` and `eliot-tree` support printing out the timestamps in the local timezone, using `--local-timezone` option. Did you need something beyond that?

**Comment by StevenLianaL** [comment]
> Both `eliot-prettyprint` and `eliot-tree` support printing out the timestamps in the local timezone, using `--local-timezone` option. Did you need something beyond that?

Thank you!
