### ISSUE TITLE
Type-hint decorator to preserve type-inference on pass-through

### ISSUE THREAD

**Issue by MartinBernstorff** [itamarst/eliot#501]
I'd love to use eliot while preserving types of the decorated functions! I can volunteer a PR adding generic types. Before I work on it, would that be of interest? :-)

**Comment by itamarst** [comment]
Yes, I'd love to have that, thank you.

**Comment by MartinBernstorff** [comment]
Huh, seems pyright already correctly infers the pass-through types! In that case, I don't think typing part of the code-base is a good idea. Apologies about not checking before creating an issue, can't wait to start using eliot 👍
