### ISSUE TITLE
Figure out if the Zipkin UI could be used to visualize Eliot logs

### ISSUE THREAD

**Issue by itamarst** [itamarst/eliot#85]
Eliot logs contain timing information that would be useful for performance analysis, the goal of Twitter's Zipkin tracing system. Their UI would be useful for this, perhaps (https://twitter.github.io/zipkin/index.html has a screenshot), which implies we'd need to load the data from Eliot somehow.

**Comment by griels** [comment]
Hi, did you make any progress with this? I'm guessing integration might be tricky as you aren't using OpenTracing AFAICT.

**Comment by itamarst** [comment]
Probably never going to do this.
